language: python

python:
  - 3.4

install:
  - pip install PyYAML==5.1.2
  - pip install mkdocs==0.16.3
  - python setup.py install

script:
  - mkdocs build --clean

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd site
    git init
    git add .
    git -c user.name=$GITHUB_MEOWJ_NAME -c user.email=$GITHUB_MEOWJ_EMAIL commit -m "Auto Deployment"
    git push -f -q https://Krasjet:$GITHUB_API_KEY@github.com/LearnOpenGL-CN/learnopengl-cn.github.io master
    cd "$TRAVIS_BUILD_DIR"
  fi
